---
# Deploy a VM from Template
- hosts: all
  #Variables for vCenter and VMs
  vars:
    vcenter_ip: ""
    vcenter_username: ""
    vcenter_password: ""
    vm_name: ""
    dc: ""
    folder: ""
    template: ""
    vm_ram: ""
    vm_cpus: ""
    vm_cpu_cores_per_socket: ""
    vm_disk_gb: ""
    vm_hostname: ""
    #vm_os: ""
    
  tasks:
    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        folder: "{{ folder }}" 
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template }}"
        disk:
        - size_gb: "{{ vm_disk_gb }}"
          type: thin
          datastore: vsanDatastore
        hardware:
          memory_mb: "{{ vm_ram }}"
          num_cpus: "{{ vm_cpus }}" #For example to create a VM with 2 sockets of 4 cores, specify num_cpus: 8 and num_cpu_cores_per_socket: 4
          num_cpu_cores_per_socket: "{{ vm_cpu_cores_per_socket }}"
          scsi: paravirtual
          #memory_reservation_lock: False
          #mem_limit: 8096
          #mem_reservation: 4096
          #cpu_limit: 8096
          #cpu_reservation: 4096
          #max_connections: 5
          #hotadd_cpu: True
          #hotremove_cpu: True
          #hotadd_memory: False
          #version: 12 # Hardware version of virtual machine
          boot_firmware: "efi"
        networks:
        - name: VM Network
          type: dhcp
        customization:
          hostname: "{{ vm_hostname }}"
        #cdrom:
        #  type: iso
        #  iso_path: "[datastore1] livecd.iso"
        #networks:
        #- name: VM Network
        #  mac: aa:bb:dd:aa:00:14
        wait_for_ip_address: yes
      delegate_to: localhost
      #register: deploy
    #- hostname:
    #  name: "{{ vm_hostname }}"
    #  use: "{{ vm_os }}"
