---
# Deploy a VM from Template
- hosts: all
  #Variables for vCenter and VMs
  vars:
    vcenter_ip: ""
    vcenter_username: ""
    vcenter_password: ""
    vm_name: ""
    dc: ""
    folder: ""
    template: ""
    datastore: ""
    vm_ram: ""
    vm_cpus: ""
    vm_cpu_cores_per_socket: ""
    vm_disk_gb: ""
    vm_hostname: ""
    vm_mac: ""
    ignition_file: ""
    testvar: { vm_name: "{{ vm_name }}", vm_ram: "8196", vm_cpus: "8" }
    
  tasks:
    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ dc }}"
        folder: "{{ folder }}" 
        name: "{{ item.vm_name }}"
        state: present
        template: "{{ template }}"
        disk:
        - size_gb: "{{ vm_disk_gb }}"
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ item.vm_ram }}"
          mem_reservation: "{{ item.vm_ram }}"
          num_cpus: "{{ item.vm_cpus }}" #For example to create a VM with 2 sockets of 4 cores, specify num_cpus: 8 and num_cpu_cores_per_socket: 4
          #num_cpu_cores_per_socket: "{{ vm_cpu_cores_per_socket }}"
          scsi: paravirtual
          boot_firmware: "efi"
        networks:
        - name: "VM Network"
          type: dhcp
      with_items:
          - "{{ testvar }}"
          - { vm_name: testworker2, vm_ram: "1024", vm_cpus: "4" }
      delegate_to: localhost
