---
- hosts: all
  vars:
    username: ""
    password: ""
    to: ""
    body: ""
  
  tasks:
    - name: Sending an e-mail
      mail:
        host: smtp.gmail.com
        port: 465
        from: "{{ from }}"
        username: "{{ username }}"
        password: "{{ password }}"
        to: "{{ to }}" #Rémi Salandre <remi.salandre@gmail.com>
        subject: OpenShift Installation
        body: "{{ body }}"
        secure: always
