---
- hosts: all
  vars:
    username: ""
    password: ""
    to: ""
  
  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: aspmx.l.google.com
        port: 25
        #username: "{{ username }}"
        #password: "{{ password }}"
        to: "{{ to }}" #Rémi Salandre <remi.salandre@gmail.com>
        subject: Test Ansible-report
        body: 'System {{ ansible_hostname }} has been successfully provisioned.'
